"""Generate TypeScript wire contracts from the application's actual OpenAPI.

No database, server or npm package is needed. --check makes contract drift
fail CI. Unsupported schema constructs fail rather than weakening a type.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from app.main import app  # noqa: E402

OUTPUT = Path(__file__).resolve().parents[2] / "frontend/src/lib/generated/api.ts"


def name(value: str) -> str:
    return re.sub(r"\W", "_", value)


def ts(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return name(schema["$ref"].rsplit("/", 1)[-1])
    if "enum" in schema:
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in schema["enum"])
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    for union in ("anyOf", "oneOf", "allOf"):
        if union in schema:
            joiner = " & " if union == "allOf" else " | "
            return "(" + joiner.join(ts(item) for item in schema[union]) + ")"
    kind = schema.get("type")
    if kind in ("string", "boolean", "null"):
        return str(kind)
    if kind in ("number", "integer"):
        return "number"
    if kind == "array":
        return f"Array<{ts(schema['items'])}>"
    if kind == "object":
        required = set(schema.get("required", []))
        fields = [
            f"  {json.dumps(key)}{'' if key in required else '?'}: {ts(value)};"
            for key, value in schema.get("properties", {}).items()
        ]
        extra = schema.get("additionalProperties")
        if extra is True:
            fields.append("  [key: string]: unknown;")
        elif isinstance(extra, dict):
            fields.append(f"  [key: string]: {ts(extra)};")
        return "{\n" + "\n".join(fields) + "\n}" if fields else "Record<string, unknown>"
    if not schema:
        return "unknown"
    raise ValueError(f"Unsupported OpenAPI schema: {schema}")


def generate() -> str:
    lines = [
        "// Generated by backend/scripts/generate_api.py. Do not edit.",
        "// Source: app.main.app.openapi(); response defaults are required."
        " Inputs remain optional.",
        "",
    ]
    for key, schema in sorted(app.openapi()["components"]["schemas"].items()):
        identifier = name(key)
        lines.append(f"export type {identifier} = {ts(schema)};\n")
        if "enum" in schema:
            values = json.dumps(schema["enum"], ensure_ascii=False)
            lines.append(f"export const {identifier}Values = {values} as const;\n")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            print(
                "API contracts are stale. Run: cd backend && uv run python scripts/generate_api.py"
            )
            return 1
        print("Generated API contracts match OpenAPI.")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(generated)
        print(f"Generated {OUTPUT.relative_to(OUTPUT.parents[4])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
